spring:
  application:
    name: blog

  # Profile settings
  profiles:
    active: dev

  # JPA settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

---
# Development profile configuration
spring:
  config:
    activate:
      on-profile: dev

  # H2 Database Configuration
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:blogdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

# Logging configuration for development
logging:
  level:
    root: INFO
    kr.null0xff.blog: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

---
# Production profile configuration
spring:
  config:
    activate:
      on-profile: prod

  # MariaDB Configuration
  datasource:
    url: jdbc:mariadb://localhost:3306/blogdb
    driverClassName: org.mariadb.jdbc.Driver
    username: bloguser
    password: blogpassword
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect

# Logging configuration for production
logging:
  level:
    root: WARN
    kr.null0xff.blog: INFO